version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    container_name: zookeeper
  kafka:
    image: wurstmeister/kafka:2.12-2.3.1
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "flight_delay_classification_request:1:1" # 1 partition and 1 replica
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    build: ./mongo
    hostname: mongo
    container_name: mongo
  flask:
    build: ./flask
    hostname: flask
    container_name: flask
    depends_on: 
      - kafka
      - mongo
    ports:
      - "5000:5000"
  spark-submit: 
    build: ./spark-submit
    container_name: spark-submit    
    user: root
    environment:
      - SPARK_MASTER_URL=local[*]
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on: 
      - kafka
      - mongo
  spark-worker-1:
    image: bitnami/spark:2.4.4
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-submit:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on: 
      - spark-submit